"""Initial migration

Revision ID: 0c8a9db379f5
Revises: 91888e1eff2b
Create Date: 2025-07-01 23:25:37.818900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8a9db379f5'
down_revision = '91888e1eff2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.drop_column('disabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disabled', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
