"""add keywords

Revision ID: 34f1c2f50b81
Revises: 686e9b22d379
Create Date: 2025-07-07 21:47:38.153759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34f1c2f50b81'
down_revision = '686e9b22d379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('media_type', sa.String(), nullable=False))
        batch_op.drop_column('provider_name')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('provider_name', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('media_type')
        batch_op.drop_column('media_name')

    # ### end Alembic commands ###
