"""add media providers

Revision ID: 54b15337698b
Revises: cbb26be33336
Create Date: 2025-07-08 20:34:08.242805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b15337698b'
down_revision = 'cbb26be33336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_slots_id'))

    op.drop_table('user_slots')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_slots',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('provider', sa.VARCHAR(), nullable=True),
    sa.Column('provider_user_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_slots_id'), ['id'], unique=False)

    # ### end Alembic commands ###
