"""add keywords

Revision ID: 686e9b22d379
Revises: bb9d9cf59789
Create Date: 2025-07-07 21:35:18.219104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686e9b22d379'
down_revision = 'bb9d9cf59789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))
        batch_op.drop_column('sub_category')
        batch_op.drop_column('keyword')
        batch_op.drop_column('language')
        batch_op.drop_column('region')
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('region', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('language', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('keyword', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('sub_category', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
