"""Initial migration

Revision ID: 91888e1eff2b
Revises: 9ec542c51695
Create Date: 2025-07-01 23:24:25.109476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91888e1eff2b'
down_revision = '9ec542c51695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_slots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_slots_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_slots_id'))

    op.drop_table('user_slots')
    # ### end Alembic commands ###
