"""add media providers

Revision ID: bb9d9cf59789
Revises: fed2780d1961
Create Date: 2025-07-07 21:27:14.706602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb9d9cf59789'
down_revision = 'fed2780d1961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_providers', schema=None) as batch_op:
        batch_op.alter_column('parameters',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_providers', schema=None) as batch_op:
        batch_op.alter_column('parameters',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
