"""add keywords

Revision ID: cbb26be33336
Revises: 34f1c2f50b81
Create Date: 2025-07-07 21:48:51.558373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb26be33336'
down_revision = '34f1c2f50b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_name', sa.String(), nullable=False))
        batch_op.drop_column('media_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('provider_name')

    # ### end Alembic commands ###
