"""add media providers

Revision ID: fed2780d1961
Revises: 8e0c38b4fbbd
Create Date: 2025-07-07 20:59:25.311115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed2780d1961'
down_revision = '8e0c38b4fbbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('client_secret', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_providers', schema=None) as batch_op:
        batch_op.drop_column('client_secret')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
